### ISSUE TITLE
Trying to use your script

### ISSUE THREAD

**Issue by roviaro** [zonoskar/Goodwe2PVoutput#1]
Hello,

Trying to use your script on MacOS-X.

After logging in on the goodwe site I get the following:
Convert data Error: list index out of range
sleep 240.0 seconds before next sample

What can this be?

Question: is historical data supported?

Regards, Rob

**Comment by zonoskar** [comment]
Hi Rob,

First of all, historical data is not supported, only the live data.

Second, the list index out of range is probably because the website gives
less entries than expected. Which inverter do you use? Does it support 2
MPPs?

Cheers, Dennis.

On Wed, Jun 22, 2016 at 7:13 PM, roviaro notifications@github.com wrote:

> Hello,
> 
> Trying to use your script on MacOS-X.
> 
> After logging in on the goodwe site I get the following:
> Convert data Error: list index out of range
> sleep 240.0 seconds before next sample
> 
> What can this be?
> 
> Question: is historical data supported?
> 
> Regards, Rob
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/zonoskar/Goodwe2PVoutput/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/ADEcg9KzZ5-VFBlfK0V3nTj9PTFGCQCkks5qOW1CgaJpZM4I8A1t
> .

## 

## 

Dennis.

**Comment by roviaro** [comment]
Hi Dennis,

I am using the Goodwe 2500. I think it supports only 1 tracker.

Regards, Rob

**Comment by zonoskar** [comment]
Hi Rob,

That explains your error. I split the response from the website into chunks
that are put in a list. Then extract
the data from the list. If the list is shorter due to only one tracker, I
will try to extract data that isn't there.

I'll try to fix this, but I cannot test this myself. Can you send me a
screenshot of th erealtime tab of the goodwe
site so I can get a feel for the data? I will need the complete line, so
you'll probably have to make more screen
shots.

Cheers, Dennis.

On Thu, Jun 23, 2016 at 1:58 PM, roviaro notifications@github.com wrote:

> Hi Dennis,
> 
> I am using the Goodwe 2500. I think it supports only 1 tracker.
> 
> Regards, Rob
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/zonoskar/Goodwe2PVoutput/issues/1#issuecomment-228028548,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADEcg-qgV55P7RfN4r7f9efmeULIIDJLks5qOnTvgaJpZM4I8A1t
> .

## 

## 

Dennis.

**Comment by roviaro** [comment]
Hi Dennis,
Understood!
Here is the screenshot:
![screen shot 2016-06-23 at 14 13 27](https://cloud.githubusercontent.com/assets/13256856/16302664/b8407240-394c-11e6-9c0b-c1721529326c.png)

How did you upload historic data or did you not needed that?

Regards, Rob

**Comment by zonoskar** [comment]
Hi Rob,

I have not needed to upload historical data. So that's why. It's also a lot
of work I guess, although I found some script for it the other day. Let me
look...

Can you complete the screenshot (scroll to the left, now only shows data
uptill Iac). It looks like although you only have one tracker, there's
still data
for both in the screenshot (Vpv and Ipv show 2 values). Also Vac and Iac
show 3 values, which in you rcase probably are meaningless since you
probably have a 1 fase inverter, right? That means that there is something
else missing.

Dennis.

On Thu, Jun 23, 2016 at 2:15 PM, roviaro notifications@github.com wrote:

> Hi Dennis,
> Understood!
> Here is the screenshot:
> [image: screen shot 2016-06-23 at 14 13 27]
> https://cloud.githubusercontent.com/assets/13256856/16302664/b8407240-394c-11e6-9c0b-c1721529326c.png
> 
> How did you upload historic data or did you not needed that?
> 
> Regards, Rob
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/zonoskar/Goodwe2PVoutput/issues/1#issuecomment-228031829,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADEcgweB8u5SZppuMZirDz1PUgtn2knMks5qOnjRgaJpZM4I8A1t
> .

## 

## 

Dennis.

**Comment by zonoskar** [comment]
https://github.com/Sp1l/PhotoVoltaic/tree/master/Goodwe2PVouput

This posts a history script, but I have not tried that yet.

Cheers, Dennis.

On Thu, Jun 23, 2016 at 2:15 PM, roviaro notifications@github.com wrote:

> Hi Dennis,
> Understood!
> Here is the screenshot:
> [image: screen shot 2016-06-23 at 14 13 27]
> https://cloud.githubusercontent.com/assets/13256856/16302664/b8407240-394c-11e6-9c0b-c1721529326c.png
> 
> How did you upload historic data or did you not needed that?
> 
> Regards, Rob
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/zonoskar/Goodwe2PVoutput/issues/1#issuecomment-228031829,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADEcgweB8u5SZppuMZirDz1PUgtn2knMks5qOnjRgaJpZM4I8A1t
> .

## 

## 

Dennis.

**Comment by roviaro** [comment]
Hi Dennis,

Sorry, the website does not scale so I just copied the data.

RealTime
NO  Status  S/N     PGrid   EDay    ETotal  HTotal(h)   Error Message   Vpv     Ipv     Vac     Iac     Fac     Temperature(℃)            SOC     Load    Consume of Day  Consume of Total
1   Normal  12500SSN163W0023    1048W   5.1kWh  303.0kWh    416h        264.2/0.0V  4.1/0.0A    232.9/0.0/0.0V  3.8/0.0/0.0A    49.98/0.00/0.00Hz   36.2℃     0.0V    0.0A    0/0%    0.0V/0.0A/0.000KW   0.0kWh  0.0kWh

I started with the script you mentioned but that not work either (and owner did not yet respond).

Regards, Rob

**Comment by zonoskar** [comment]
Hmm, looks like all the data is there...

Did you get a stach trace with the python error?

Cheers, Dennis.

On Thu, Jun 23, 2016 at 2:34 PM, roviaro notifications@github.com wrote:

> Hi Dennis,
> 
> Sorry, the website does not scale so I just copied the data.
> 
> RealTime
> NO Status S/N PGrid EDay ETotal HTotal(h) Error Message Vpv Ipv Vac Iac
> Fac Temperature(℃) SOC Load Consume of Day Consume of Total
> 1 Normal 12500SSN163W0023 1048W 5.1kWh 303.0kWh 416h 264.2/0.0V 4.1/0.0A
> 232.9/0.0/0.0V 3.8/0.0/0.0A 49.98/0.00/0.00Hz 36.2℃ 0.0V 0.0A 0/0%
> 0.0V/0.0A/0.000KW 0.0kWh 0.0kWh
> 
> I started with the script you mentioned but that not work either (and
> owner did not yet respond).
> 
> Regards, Rob
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/zonoskar/Goodwe2PVoutput/issues/1#issuecomment-228036140,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADEcg5loHu0r5VJ1gzQKS5SqVbC9zelJks5qOn1vgaJpZM4I8A1t
> .

## 

## 

Dennis.

**Comment by zonoskar** [comment]
Hi,

Did you get the script to run? Or are you still experiencing problems?

Cheers, Dennis.

On Thu, Jun 23, 2016 at 2:34 PM, roviaro notifications@github.com wrote:

> Hi Dennis,
> 
> Sorry, the website does not scale so I just copied the data.
> 
> RealTime
> NO Status S/N PGrid EDay ETotal HTotal(h) Error Message Vpv Ipv Vac Iac
> Fac Temperature(℃) SOC Load Consume of Day Consume of Total
> 1 Normal 12500SSN163W0023 1048W 5.1kWh 303.0kWh 416h 264.2/0.0V 4.1/0.0A
> 232.9/0.0/0.0V 3.8/0.0/0.0A 49.98/0.00/0.00Hz 36.2℃ 0.0V 0.0A 0/0%
> 0.0V/0.0A/0.000KW 0.0kWh 0.0kWh
> 
> I started with the script you mentioned but that not work either (and
> owner did not yet respond).
> 
> Regards, Rob
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/zonoskar/Goodwe2PVoutput/issues/1#issuecomment-228036140,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADEcg5loHu0r5VJ1gzQKS5SqVbC9zelJks5qOn1vgaJpZM4I8A1t
> .

## 

## 

Dennis.
